### ISSUE TITLE
Wingman formula force assetto corsa 

### ISSUE THREAD

**Issue by trianths1** [timschumi/iforce-binary-driver#12]
Could you list that for playing Assetto Corsa with the Wingman Formula Force you need to enable the force 32bit setting?

**Comment by timschumi** [comment]
I'm currently not at a computer to test this myself. Are you sure that the issue you are having is related to a 32-bit/64-bit switch? In theory the joystick inputs should be properly abstracted away, so the driver doesn't care if the application is 32-bit or 64-bit.

**Comment by trianths1** [comment]
I'm not sure, but this without the force 32bit the game crashed while
loading

**Comment by TheFlano23** [comment]
Same problem on my end as documented on #13. Forcing 32 bit allows the game to run albeit at a poor framerate

**Comment by timschumi** [comment]
Circumstances indicate that this might be another occurrence of #9. Closing in favor of that issue, please reopen in case [these](https://github.com/timschumi/iforce-binary-driver/issues/13#issuecomment-2338118790) instructions don't solve the issue for you.
